# Activations Manager

This notebook includes cells to perform different kinds of data manipulation with the activations

## Import libraries

In [1]:
from activations import *

from utils import ACTIVATIONS_FOLDER, MODELS_FOLDER, LANGUAGES, SPLITS, MODEL_NAMES
from icecream import ic

device: t.device = t.device("cuda" if t.cuda.is_available() else "cpu")
device

device(type='cuda')

## Activation Generator

In [2]:
save_to_disk: bool = True
amount_of_batches_to_generate: int | None = None
batch_size: int = 128
# model_name: str = "aya_expanse"
languages_to_generate: list[str] = LANGUAGES
splits_to_generate: list[str] = SPLITS

debug = False
if debug:
    languages_to_generate = ["en"]
    languages_to_generate = LANGUAGES
    splits_to_generate = ["train"]
    amount_of_batches_to_generate = 2
    batch_size = 4
    print("Running in debug mode")

ic(save_to_disk, amount_of_batches_to_generate, batch_size, languages_to_generate, splits_to_generate)


assert save_to_disk, ("If generating, must also save to disk")

ic| save_to_disk: True
    amount_of_batches_to_generate: None
    batch_size: 128
    languages_to_generate: ['en', 'es', 'nl', 'jp']
    splits_to_generate: ['train', 'test', 'val']


In [ ]:
languages_to_generate = ["jp"]
batch_size = 64

model_name: str = "olmo_model"

activation_recorder: ActivationRecorder = ActivationRecorder(model_name)

special_cases: list[SpecialCase] = []    

activation_recorder.generate_all_activations(
    languages_to_generate,
    splits_to_generate,
    amount_of_batches_to_generate,
    save_to_disk,
    batch_size,
    special_cases=special_cases,
)

In [ ]:
languages_to_generate = LANGUAGES

# Aya Expanse is an 8B model, so it needs a smaller batch size than the 128 set above
# to fit alongside its activations on the GPU.
batch_size = 16

model_name: str = "aya_expanse"

activation_recorder: ActivationRecorder = ActivationRecorder(model_name)

special_cases: list[SpecialCase] = []    

activation_recorder.generate_all_activations(
    languages_to_generate,
    splits_to_generate,
    amount_of_batches_to_generate,
    save_to_disk,
    batch_size,
    special_cases=special_cases,
)

## Sanity Checks

In [6]:
model_names: list[str] = MODEL_NAMES
languages: list[str] = LANGUAGES
splits: list[str] = SPLITS

custom = False
if custom:
    model_names = ["olmo_model"]
    languages = ["en"]
    splits = ["train"]
    print(f"Using custom configuration")
    ic(model_names, languages, splits)

for model_name in model_names:
    for language in languages:
        for split in splits:
            activations_dataset: ActivationDataset = ActivationDataset(language, split, 0, "standard", model_name)

            print(activations_dataset.activations.shape)
            for i in range(8):
                print(activations_dataset[i][0])
                print(activations_dataset[i][1])
                print("\n-----------------")

torch.Size([4439, 4096])
tensor([-0.0092, -0.0142,  0.0153,  ..., -0.0130, -0.0105,  0.0016],
       dtype=torch.bfloat16)
tensor(1, dtype=torch.int32)

-----------------
tensor([-0.0092, -0.0148,  0.0160,  ..., -0.0131, -0.0108,  0.0012],
       dtype=torch.bfloat16)
tensor(1, dtype=torch.int32)

-----------------
tensor([-0.0088, -0.0155,  0.0140,  ..., -0.0131, -0.0098,  0.0021],
       dtype=torch.bfloat16)
tensor(0, dtype=torch.int32)

-----------------
tensor([-0.0089, -0.0142,  0.0147,  ..., -0.0131, -0.0100,  0.0022],
       dtype=torch.bfloat16)
tensor(1, dtype=torch.int32)

-----------------
tensor([-0.0089, -0.0154,  0.0154,  ..., -0.0129, -0.0107,  0.0014],
       dtype=torch.bfloat16)
tensor(1, dtype=torch.int32)

-----------------
tensor([-0.0089, -0.0160,  0.0123,  ..., -0.0135, -0.0060,  0.0039],
       dtype=torch.bfloat16)
tensor(1, dtype=torch.int32)

-----------------
tensor([-0.0091, -0.0157,  0.0142,  ..., -0.0137, -0.0082,  0.0018],
       dtype=torch.bfloat16)
t

## Activation Merger

In [5]:
model_names: list[str] = MODEL_NAMES
languages: list[str] = LANGUAGES
splits: list[str] = SPLITS

custom = True
if custom:
    model_names = ["aya_expanse"]
    print("Using custom configuration")
else:
    print("Using default configuration")

ic(model_names, languages, splits, custom)

for model_name in model_names:
    num_layers: int = ActivationRecorder(model_name).get_number_of_layers()
    for language in languages:
        for split in splits:
            try:
                for layer_num in range(num_layers):
                    print(f"Merging {model_name}/{language}/{split}")
                    merge_activation_batches(model_name, language, split, layer_num)
            except FileNotFoundError as e:
                print(f"Couldn't merge activations of {model_name}, {language}, {split} due to:\n {e}")
                print("It is possible that these activations were already merged")

ic| model_names: ['aya_expanse']
    languages: ['en', 'es', 'nl', 'jp']
    splits: ['train', 'test', 'val']
    custom: True


Using custom configuration
Model not loaded. Getting the number of layers from ./data/activations/aya_expanse/n_layers.txt
Merging aya_expanse/en/train
Merged 278 batch files for aya_expanse, en, train, layer0
Merged activations shape: torch.Size([4439, 4096])
Saved to ./data/activations/aya_expanse/en/train/layer0_merged.pt
Merging aya_expanse/en/train
Merged 278 batch files for aya_expanse, en, train, layer1
Merged activations shape: torch.Size([4439, 4096])
Saved to ./data/activations/aya_expanse/en/train/layer1_merged.pt
Merging aya_expanse/en/train
Merged 278 batch files for aya_expanse, en, train, layer2
Merged activations shape: torch.Size([4439, 4096])
Saved to ./data/activations/aya_expanse/en/train/layer2_merged.pt
Merging aya_expanse/en/train
Merged 278 batch files for aya_expanse, en, train, layer3
Merged activations shape: torch.Size([4439, 4096])
Saved to ./data/activations/aya_expanse/en/train/layer3_merged.pt
Merging aya_expanse/en/train
Merged 278 batch files for aya_e

## Activation Deleter

In [9]:
# models_to_delete: list[str] = ["olmo_model"]
# languages_to_delete: list[str] = ["es"]
models_to_delete: list[str] = MODEL_NAMES
languages_to_delete: list[str] = LANGUAGES
splits_to_delete: list[str] = SPLITS

ignore_substring = "merged"
# ignore_substring = "batch"

actually_delete = True

for model_name in models_to_delete:
    for language in languages_to_delete:
        for split in splits_to_delete:
            delete_activations_file(model_name, language, split, layer_num=None, batch_id=None, ignore_substring=ignore_substring, actually_delete=actually_delete)


Deleted data\activations\olmo_model\en\train\layer0_batch0.pt
Deleted data\activations\olmo_model\en\train\layer0_batch1.pt
Deleted data\activations\olmo_model\en\train\layer0_batch10.pt
Deleted data\activations\olmo_model\en\train\layer0_batch11.pt
Deleted data\activations\olmo_model\en\train\layer0_batch12.pt
Deleted data\activations\olmo_model\en\train\layer0_batch13.pt
Deleted data\activations\olmo_model\en\train\layer0_batch14.pt
Deleted data\activations\olmo_model\en\train\layer0_batch15.pt
Deleted data\activations\olmo_model\en\train\layer0_batch16.pt
Deleted data\activations\olmo_model\en\train\layer0_batch17.pt
Deleted data\activations\olmo_model\en\train\layer0_batch18.pt
Deleted data\activations\olmo_model\en\train\layer0_batch19.pt
Deleted data\activations\olmo_model\en\train\layer0_batch2.pt
Deleted data\activations\olmo_model\en\train\layer0_batch20.pt
Deleted data\activations\olmo_model\en\train\layer0_batch21.pt
Deleted data\activations\olmo_model\en\train\layer0_batch2