In [ ]:
from common_constants import SPLITS
from sick_loader import SICKMergedDataset
from activations_loader import ActivationDataset

Check the total number of elements in the sick merged dataset

In [ ]:
# all_sick_merged_elements = []
number_of_elements = 0
language = "en"

for split in SPLITS:
    sick_merged_dataset = SICKMergedDataset(language, split)
    for sick_merged_element in sick_merged_dataset:
        # print(sick_merged_element, number_of_elements)
        # all_sick_merged_elements.append(sick_merged_element)
        number_of_elements += 1

# print(all_sick_merged_elements)
print(number_of_elements)

9840


Check that the activations make sense

In [ ]:
activations_dataset = ActivationDataset("en", "train", 0, "standard", "olmo_model")

for i in range(8):
    print(f"{activations_dataset[i]}\n-----------------")

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 1, 1], dtype=torch.int32)
tensor([2, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 1, 1, 1, 0, 2, 1, 1, 0, 2, 1, 1,
        2, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 0, 2, 0], dtype=torch.int32)
tensor([1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1,
        1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 0,
        1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1], dtype=torch.int32)
tensor([1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 2, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 0, 2,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 0, 1, 1, 0, 2, 1, 1, 1, 1, 1, 2, 1, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1], dtype=torch.int32)
(tensor([-0.0674, -0.0009,  0.0159,  ...,  0.0479, -0.07